const fs = require("fs");

const OUT = "generated";

fs.mkdirSync(OUT, { recursive: true });

const darkBanner = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="1180"
     height="610"
     viewBox="0 0 1180 610">

  <rect width="1180" height="610" fill="#0A101F"/>

  <rect x="20" y="20"
        width="1140"
        height="570"
        rx="16"
        fill="#0A101F"
        stroke="#22D3EE"
        stroke-width="2"/>

  <rect x="20" y="20"
        width="1140"
        height="55"
        rx="16"
        fill="#111A2E"/>

  <circle cx="50" cy="47" r="7" fill="#EF4444"/>
  <circle cx="75" cy="47" r="7" fill="#F59E0B"/>
  <circle cx="100" cy="47" r="7" fill="#10B981"/>

  <text x="590"
        y="54"
        text-anchor="middle"
        fill="#CBD5E1"
        font-family="monospace"
        font-size="16">
    profile.sh --live
  </text>

  <rect x="45" y="100"
        width="410"
        height="450"
        rx="14"
        fill="#0F172A"
        stroke="#22D3EE"
        stroke-width="1.5"/>

  <text x="65"
        y="125"
        fill="#22D3EE"
        font-family="monospace"
        font-size="13">
    VISUAL.MAP
  </text>

  <rect x="55" y="140"
        width="390"
        height="385"
        rx="10"
        fill="#0A101F"/>

  <text x="250"
        y="325"
        text-anchor="middle"
        fill="#A78BFA"
        font-family="monospace"
        font-size="20">
    PORTRAIT
  </text>

  <text x="250"
        y="350"
        text-anchor="middle"
        fill="#64748B"
        font-family="monospace"
        font-size="12">
    GENERATED BY GITHUB ACTIONS
  </text>

  <text x="500"
        y="120"
        fill="#22D3EE"
        font-family="monospace"
        font-size="13">
    SYSTEM.INFO
  </text>

  <circle cx="1070"
          cy="116"
          r="5"
          fill="#EF4444">
    <animate attributeName="opacity"
             values="1;0.2;1"
             dur="1.2s"
             repeatCount="indefinite"/>
  </circle>

  <text x="1085"
        y="121"
        fill="#EF4444"
        font-family="monospace"
        font-size="12">
    LIVE
  </text>

  <rect x="500"
        y="140"
        width="310"
        height="34"
        rx="17"
        fill="#10B981"/>

  <text x="655"
        y="163"
        text-anchor="middle"
        fill="#061018"
        font-family="monospace"
        font-size="14"
        font-weight="bold">
    @SandhyaMadhusuthanan
  </text>

  <g font-family="monospace" font-size="14">

    <text x="500" y="215" fill="#94A3B8">Subject</text>
    <text x="770" y="215" fill="#E2E8F0">Sandhya Madhu</text>

    <text x="500" y="238" fill="#94A3B8">Role</text>
    <text x="770" y="238" fill="#E2E8F0">
      B.Com Business Analytics Student
    </text>

    <text x="500" y="261" fill="#94A3B8">Origin</text>
    <text x="770" y="261" fill="#E2E8F0">
      Coimbatore, India
    </text>

    <text x="500" y="284" fill="#94A3B8">Education</text>
    <text x="770" y="284" fill="#E2E8F0">
      B.Com Business Analytics
    </text>

    <text x="500" y="307" fill="#94A3B8">Status</text>
    <text x="770" y="307" fill="#10B981">
      Learning + Building + Exploring
    </text>

    <text x="500" y="330" fill="#94A3B8">ToolChain</text>
    <text x="770" y="330" fill="#E2E8F0">
      GitHub · VS Code · Excel
    </text>

    <text x="500" y="368" fill="#22D3EE">
      CORE
    </text>

    <text x="500" y="392" fill="#94A3B8">Core.Lang</text>
    <text x="770" y="392" fill="#E2E8F0">
      R · SQL
    </text>

    <text x="500" y="415" fill="#94A3B8">Core.Frontend</text>
    <text x="770" y="415" fill="#E2E8F0">
      HTML · CSS
    </text>

    <text x="500" y="438" fill="#94A3B8">Core.Backend</text>
    <text x="770" y="438" fill="#64748B">
      —
    </text>

    <text x="500" y="461" fill="#94A3B8">Core.Database</text>
    <text x="770" y="461" fill="#E2E8F0">
      MySQL
    </text>

    <text x="500" y="484" fill="#94A3B8">Core.Infra</text>
    <text x="770" y="484" fill="#E2E8F0">
      GitHub
    </text>

  </g>

  <line x1="500"
        y1="510"
        x2="1125"
        y2="510"
        stroke="#1E293B"/>

  <text x="500"
        y="535"
        fill="#64748B"
        font-family="monospace"
        font-size="12">
    GRID.SYSTEM // PROFILE.NODE // 001
  </text>

</svg>`;

const lightBanner = darkBanner
  .replaceAll("#0A101F", "#F8FAFC")
  .replaceAll("#0F172A", "#FFFFFF")
  .replaceAll("#111A2E", "#E2E8F0")
  .replaceAll("#CBD5E1", "#334155")
  .replaceAll("#94A3B8", "#475569")
  .replaceAll("#E2E8F0", "#0F172A")
  .replaceAll("#64748B", "#64748B")
  .replaceAll("#1E293B", "#CBD5E1");

fs.writeFileSync(
  `${OUT}/banner-dark.svg`,
  darkBanner
);

fs.writeFileSync(
  `${OUT}/banner-light.svg`,
  lightBanner
);

console.log("Banner files generated.");
